### PR TITLE
Support cache behaviors

### PR DESCRIPTION
**Pull request by osterman**
## what
* Add support for `cache_behaviors` 
* Support whitelisted cookie names

## why
* To enable of fine-grained cache rules for applications like wordpress
* To pass cookies to origin for stateful applications like wordpress

### CODE REVIEW

**Comment by wolstena** [comment]
I'd like to tryout the new cache behaviours  element in the module. I think I'm close but the plan  I have created is failing on the forwarded_values definition.  Do you have a sample of a working config to help get me started. Cheers.

`module 'cdn' {
...
cache_behavior = "${var.cache_behavior}"
}`

`
variable "cache_behavior" {
  type = "list"
  default = 
  [{
    path_pattern = "/login/*"
    target_origin_id = "cx-dev-easy"
    allowed_methods  = ["DELETE", "GET", "HEAD", "OPTIONS", "PATCH", "POST", "PUT"]
    cached_methods = ["GET","HEAD"]
    compress = true
    smooth_streaming = false
    forwarded_values  {
      cookies {
        forward = "none"
      }
      headers = ["Host"]
      query_string = true
    }
    viewer_protocol_policy = "allow-all"
    min_ttl = 0
    default_ttl = 0
    max_ttl = 0
  }]
}
`

The error:
module.cdn.aws_cloudfront_distribution.default: cache_behavior.0.forwarded_values: should be a list

**Comment by aknysh** [comment]
@wolstena  thank you for trying out the module.
we'll look into the issue

**Comment by osterman** [comment]
Here's how I do it for `www.cloudposse.com`:

```
provider "aws" {
  region = "us-east-1"
}

terraform {
  required_version = ">= 0.10.7"
  backend          "s3"             {}
}

locals {
  wp_nocache_behavior = {
    viewer_protocol_policy = "redirect-to-https"
    cached_methods         = ["GET", "HEAD"]
    allowed_methods        = ["HEAD", "DELETE", "POST", "GET", "OPTIONS", "PUT", "PATCH"]
    default_ttl            = 60
    min_ttl                = 0
    max_ttl                = 86400
    compress               = "true"
    target_origin_id       = "cp-prod-wordpress-cloudposse.com"

    forwarded_values = [{
      headers      = ["*"]
      query_string = "true"

      cookies = [{
        forward = "all"
      }]
    }]
  }
}

# CloudFront CDN fronting origin
module "cdn" {
  source     = "git::https://github.com/cloudposse/terraform-aws-cloudfront-cdn.git?ref=support-cache-behaviors"
  namespace  = "cp"
  stage      = "prod"
  name       = "wordpress"
  attributes = ["cloudposse.com"]

  aliases                           = ["cloudposse.com", "www.cloudposse.com"]
  origin_domain_name                = "origin.cloudposse.com"
  origin_protocol_policy            = "match-viewer"
  viewer_protocol_policy            = "redirect-to-https"
  parent_zone_name                  = "cloudposse.com"
  default_root_object               = ""
  acm_certificate_arn               = "arn:aws:acm:us-east-1:313021614177:certificate/2dc2b7f9-af74-4c68-ba89-cdfbcbd3e92c"
  forward_cookies                   = "whitelist"
  forward_cookies_whitelisted_names = ["comment_author_*", "comment_author_email_*", "comment_author_url_*", "wordpress_logged_in_*", "wordpress_test_cookie", "wp-settings-*"]
  forward_headers                   = ["Host", "Origin", "Access-Control-Request-Headers", "Access-Control-Request-Method"]
  forward_query_string              = "true"
  default_ttl                       = 60
  min_ttl                           = 0
  max_ttl                           = 86400
  compress                          = "true"
  cached_methods                    = ["GET", "HEAD"]
  allowed_methods                   = ["GET", "HEAD", "OPTIONS"]
  price_class                       = "PriceClass_All"

  cache_behavior = [
    "${merge(local.wp_nocache_behavior, map("path_pattern", "wp-admin/*"))}",
    "${merge(local.wp_nocache_behavior, map("path_pattern", "wp-login.php"))}",
    "${merge(local.wp_nocache_behavior, map("path_pattern", "wp-signup.php"))}",
    "${merge(local.wp_nocache_behavior, map("path_pattern", "wp-trackback.php"))}",
    "${merge(local.wp_nocache_behavior, map("path_pattern", "wp-cron.php"))}",
    "${merge(local.wp_nocache_behavior, map("path_pattern", "xmlrpc.php"))}",
  ]
}
```

**Comment by aknysh** [comment]
@wolstena  we added a complete (working) example on how to setup a WordPress site with different Cache Behaviors in https://github.com/cloudposse/terraform-aws-cloudfront-cdn/releases/tag/0.5.1

Let us know if you have other questions or need help

**Comment by wolstena** [comment]
@osterman @aknysh thanks for the quick response. This helped out enormously. Such a elegant and tidy solution. Thanks for sharing.

**Pull request merged**
