### PR TITLE
Upgrade to 0.12

### PR DESCRIPTION
**Pull request by geota**
This is the remaining work to finish off rverma-nikiai fork in case. I submitted a PR to the upstream repo. Happy to close this and work through the existing PR if you prefer.

I was able to get it to successfully run by fixing 0.12 upgrade bug from wrapping var.custom_error_response around wrapping it in a list.

Also pinned modules to published upstream cloudposse versions with 0.12 support.

Thanks!

### CODE REVIEW

**Comment by geota** [comment]
There are two remaining TF-UPGRADE-TODO comments that need to be stripped. I confirmed that it seems they all can be set in practice by cross-checking the TF docs on the resources. TBH, Im not sure I understand the upgrade note.

**Comment by geota** [comment]
The build box needs to be updated to >0.12 terraform.

Reading through the build-harness scripts, it looks like it keys off TERRAFORM_VERSION env var. This looks fixed in the upstream build-harness repo but I am unsure how its managed on your travis buildboxes. 
  https://github.com/cloudposse/build-harness/blob/master/modules/terraform/Makefile

**Comment by Folinus** [comment]
The custom_error_response type was causing an issue for me. I was able to fix with the change to the type below.

`
variable "custom_error_response" {
  # http://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/custom-error-pages.html#custom-error-pages-procedure
  # https://www.terraform.io/docs/providers/aws/r/cloudfront_distribution.html#custom-error-response-arguments
  description = "(Optional) - List of one or more custom error response element maps"

  type    = list
  default = []
}
`

**Comment by gyoza** [comment]
Changing the list actually doesn't work if you plan on using any custom error codes..

**Comment by caevv** [comment]
Any plan to merge this?

**Comment by geota** [comment]
@caevv i actually shifted to using terraform-aws-cloudfront-s3-cdn instead and my personal forked diverged from upstream bc of individual requirements from my stack/company.

Im happy to help get this branch cleaned up to be merged if its still needed.

**Comment by geota** [comment]
Ill address the proper variable type for custom_error_response and take @gyoza suggestion, but I am no longer in a good position to test these changes.

**Comment by caevv** [comment]
Hi @geota, I'm using this one as my source is not S3, is an API.
Thanks for looking at this.

**Pull request closed without merging**
