### PR TITLE
Adding custom_origins variable

### PR DESCRIPTION
**Pull request by justnom**
## what
* Adding the ability to add multiple origins
* Duplicated from: https://github.com/cloudposse/terraform-aws-cloudfront-s3-cdn/pull/78

## why
* Allow more origins to be referenced in the `ordered_cache` block.

### CODE REVIEW

**Comment by justnom** [comment]
@nitrocode Could I please get another test on this? Thanks!

**Comment by jamengual** [comment]
can you you run `make readme` @justnom

**Comment by justnom** [comment]
@jamengual Done!

I also fixed the behaviour for the `forwarded_values` in https://github.com/cloudposse/terraform-aws-cloudfront-cdn/pull/61/commits/92ba01b40d99618ab6a3343de99825086f4ca6cf, I hope this isn't overkill. I wanted to deal with both empty strings and null values.

**Review by jamengual — APPROVED** [review]

**Pull request merged**
