### PR TITLE
Add missing inputs to the wordpress example

### PR DESCRIPTION
**Pull request by evertonevaristo**
There are two missing properties in the locals dict, 

    cache_policy_id             = ""
    origin_request_policy_id    = ""

## what
* Describe high-level what changed as a result of these commits (i.e. in plain-english, what do these changes mean?)
* Use bullet points to be concise and to the point.

## why
* Provide the justifications for the changes (e.g. business case). 
* Describe why these changes were made (e.g. why do these commits fix the problem?)
* Use bullet points to be concise and to the point.

## references
* Link to any supporting github issues or helpful documentation to add some context (e.g. stackoverflow). 
* Use `closes #123`, if this PR closes a GitHub issue `#123`

### CODE REVIEW

**Comment by nitrocode** [comment]
What are you trying to fix here? Is the example not working?

**Comment by evertonevaristo** [comment]
what
The example script will work as expected. 

why
There's a lack of two parameters in the wordpress example...

```
cache_policy_id             = ""
origin_request_policy_id    = ""
```

**Comment by evertonevaristo** [comment]
> What are you trying to fix here? Is the example not working?
> 
> Do you mind filling out the `what` and the `why` in the PR template ? These explanations help give us some context.

Yes! the example isnt working... (it's my first commit on a public repo, so.. I'm really newbie on this...)

**Review by nitrocode — APPROVED** [review]

**Pull request merged**
