### PR TITLE
add custom_header variable to send custom headers to origin

### LINKED ISSUE #46: Add support for sending custom headers to origin
Have a question? Please checkout our [Slack Community](https://slack.cloudposse.com) or visit our [Slack Archive](https://archive.sweetops.com/). 

[Slack Community](https://slack.cloudposse.com)

## Describe the Feature

A common use case of CloudFront is to front traffic to an origin. To only allow traffic to a origin through CloudFront, a common method is to specify a header that is injected by CloudFront to all requests going to the origin. This Terraform module should support that feature.

## Expected Behavior

A user should be able to specify a number of headers, which are then expressed by a CloudFront distribution.

## Use Case

To authorize traffic from CloudFront as a sole source.

## Describe Ideal Solution

Only a specific (or several specific) CloudFront distributions can send traffic to a ALB.

## Alternatives Considered

Ingress for a ALB can be locked down to a set of CIDRs, but then anybody who can create CloudFront distributions can access the origins. More control is needed.

### PR DESCRIPTION
**Pull request by bkero**
## what
* Adds the ability to specify custom headers that are sent to the origin for requests

## why
* To facilitate the common pattern of only allowing traffic to origins that come form a certain CloudFront CDN, or for other use cases

## references
closes #46

### CODE REVIEW

**Comment by mihaiplesa** [comment]
Seems to have failed `bats` with:

```
ERROR: unsatisfiable constraints:
  json2hcl (missing):
    required by: world[json2hcl]
make: *** [Makefile.alpine:4: deps] Error 1
Error: Process completed with exit code 2.
```

**Comment by mihaiplesa** [comment]
@osterman any chance we can retest this?

**Review by joe-niland — APPROVED** [review]

**Comment by joe-niland** [comment]
@mihaiplesa thanks for your contribution!

**Comment by mihaiplesa** [comment]
Credit goes to @bkero here at Brave. Thanks for helping on a Sunday!

**Comment by joe-niland** [comment]
@mihaiplesa my mistake!
Thanks for the PR @bkero !

**Pull request merged**
