### PR TITLE
Adding cache_policy_id to default and ordered behaviours

### PR DESCRIPTION
**Pull request by justnom**
## what
* Adding `cache_policy_id` to the `aws_cloudfront_distribution` resource.

## why
* We want to provide a [`cloudfront_cache_policy` ](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/cloudfront_cache_policy) resource to the module.

## references
* [`aws_cloudfront_distribution` Terraform docs](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/cloudfront_distribution#cache_policy_id)

### CODE REVIEW

**Review by jamengual — DISMISSED** [review]

**Comment by justnom** [comment]
Thanks @jamengual

**Comment by justnom** [comment]
@jamengual 

Seems [terratest is failing](https://github.com/cloudposse/actions/runs/2098781225?check_suite_focus=true#step:9:166) due to another unrelated issue.

**Comment by joe-niland** [comment]
@jamengual looks like the logs bucket is not getting deleted by aws-nuke.
I noticed the module allows specifying `log_bucket_fqdn` so perhaps it can be created externally with a random name for this test?

**Comment by joe-niland** [comment]
Added PR #58 which should fix the issue with tests. Once that is merged, this one should be OK.

**Review by joe-niland — APPROVED** [review]

**Review by osterman — APPROVED** [review]

**Comment by joe-niland** [comment]
@justnom thank you for your contribution!

**Pull request merged**
