### PR TITLE
feat: update to context

### PR DESCRIPTION
**Pull request by syphernl**
## what
* Update to `context.tf`
* renamed original `enabled` to `distribution_enabled` (**breaking change**)

## why
* Most/all other CloudPosse modules have an `enabled` flag to prevent resources from being created. This module used `enabled` to toggle the status of the distribution itself.

## references
* Builds upon https://github.com/cloudposse/terraform-aws-cloudfront-cdn/pull/37, which **must be merged first**
* Fixes https://github.com/cloudposse/terraform-aws-cloudfront-cdn/issues/30

### CODE REVIEW

**Comment by nitrocode** [comment]
Hm that's a good point but it would be better to cherry pick the enabled commits into a separate pr in case the other pending pr takes longer to complete.

**Comment by syphernl** [comment]
> Hm that's a good point but it would be better to cherry pick the enabled commits into a separate pr in case the other pending pr takes longer to complete.

@nitrocode I agree that a separate PR would be a better idea but the current master is based on Terraform prior to 0.12, which is lacking functions like [try](https://www.terraform.io/docs/configuration/functions/try.html) on which these changes depend.

**Comment by aknysh** [comment]
@syphernl thanks for the PR, this is good.
We are actually updating all modules to a new convention: using `context.tf` which has all the commonly used variables like `namespace`, `environment`, `stage`, `name`, enabled`, etc.
Please see this PR as an example https://github.com/cloudposse/terraform-aws-efs/pull/55
I'd update this PR for to the new convention since we are going to do it to all modules.
Thanks

**Comment by syphernl** [comment]
@aknysh I've updated the PR (and title/description since the scoped changed somewhat)

**Pull request closed without merging**
